### ISSUE TITLE
Polish flag

### ISSUE THREAD

**Issue by JonasTisell** [BetaHuhn/countryPicker#166]
The flag for Poland is wrong. The red should be at bottom, not top.

**Comment by BetaHuhn** [comment]
Yeah you are right! The flags are crowdsourced and sometimes they are added incorrectly.

Feel free to [add](https://flags.mxis.ch/add) the correct version yourself :)

**Comment by JonasTisell** [comment]
I will! Will the wrong one be removed?

**Comment by BetaHuhn** [comment]
The issue should be fixed!

> Will the wrong one be removed?

Yes I removed it.
